"use client";
import { useCallback, useEffect, useState } from "react";
import { ArrowClockwise, CheckCircle, ShieldCheck } from "@phosphor-icons/react";
import { createSaunaApiClient, humanizeApiError } from "@/lib/sauna-api";
import { useSaunaStore } from "@/store/sauna-store";
import type { CatalogRequest, CatalogRequestStatus } from "@/types/sauna";
const options: {value:CatalogRequestStatus;label:string}[]=[{value:"submitted",label:"已提交"},{value:"reviewing",label:"评估中"},{value:"approved",label:"已排期"},{value:"distilling",label:"蒸馏中"},{value:"fulfilled",label:"已完成"},{value:"rejected",label:"不处理"}];
export function AdminCatalogRequests(){const token=useSaunaStore(s=>s.token);const admin=useSaunaStore(s=>s.identity?.permissions?.is_admin);const [items,setItems]=useState<CatalogRequest[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");const load=useCallback(async(showLoading=true)=>{if(!token||!admin)return;if(showLoading)setLoading(true);try{const r=await createSaunaApiClient(token).listAdminCatalogRequests();setItems(r.items??[]);}catch(e){setError(humanizeApiError(e));}finally{setLoading(false)}},[admin,token]);useEffect(()=>{if(!token||!admin)return;let active=true;void createSaunaApiClient(token).listAdminCatalogRequests().then(r=>{if(active){setItems(r.items??[]);setLoading(false)}}).catch(e=>{if(active){setError(humanizeApiError(e));setLoading(false)}});return()=>{active=false}},[admin,token]);async function update(item:CatalogRequest,status:CatalogRequestStatus,note:string){if(!token)return;setBusy(item.id);try{const next=await createSaunaApiClient(token).updateAdminCatalogRequest(item.id,{status,admin_note:note});setItems(v=>v.map(x=>x.id===next.id?next:x));}catch(e){setError(humanizeApiError(e));}finally{setBusy("")}}
if(!admin)return <div className="rounded-[32px] border border-[color:var(--sauna-line)] bg-[var(--sauna-panel-strong)] p-8"><ShieldCheck size={28}/><h1 className="sauna-display mt-4 text-4xl">此页面仅管理员可见。</h1></div>;
return <section className="pb-10"><div className="flex items-end justify-between gap-4"><div><p className="text-sm text-[var(--sauna-accent-strong)]">管理工作台</p><h1 className="sauna-display mt-2 text-5xl tracking-[-0.055em]">人物申请</h1></div><button onClick={()=>void load()} className="grid size-11 place-items-center rounded-full bg-[var(--sauna-soft)]"><ArrowClockwise size={17}/></button></div>{error?<p className="mt-5 text-sm text-[var(--sauna-danger)]">{error}</p>:null}<div className="mt-7 grid gap-4">{loading?<div className="h-40 animate-pulse rounded-[28px] bg-[var(--sauna-soft)]"/>:items.length?items.map(item=><AdminRequestCard key={item.id} item={item} busy={busy===item.id} onSave={update}/>):<p className="rounded-[28px] bg-[var(--sauna-panel)] p-8 text-sm text-[var(--sauna-muted)]">目前没有待处理申请。</p>}</div></section>}
function AdminRequestCard({item,busy,onSave}:{item:CatalogRequest;busy:boolean;onSave:(item:CatalogRequest,status:CatalogRequestStatus,note:string)=>void}){const [status,setStatus]=useState(item.status);const [note,setNote]=useState(item.admin_note);return <article className="rounded-[28px] border border-[color:var(--sauna-line)] bg-[var(--sauna-panel-strong)] p-6 shadow-[var(--sauna-shadow-soft)]"><div className="grid gap-6 lg:grid-cols-[1fr_360px]"><div><div className="flex flex-wrap items-center gap-3"><h2 className="sauna-display text-3xl">{item.target_name}</h2><span className="rounded-full bg-[var(--sauna-soft)] px-3 py-1 text-xs text-[var(--sauna-muted-strong)]">{item.follower_count} 人关注</span></div><p className="mt-2 text-xs text-[var(--sauna-muted)]">申请人 {item.requester_email||"用户"}</p><p className="mt-4 text-sm leading-7 text-[var(--sauna-muted-strong)]">{item.reason||"未填写申请理由。"}</p></div><div className="grid gap-3"><select value={status} onChange={e=>setStatus(e.target.value as CatalogRequestStatus)} className="h-11 rounded-[16px] border border-[color:var(--sauna-line)] bg-[var(--sauna-soft)] px-3 text-sm">{options.map(x=><option key={x.value} value={x.value}>{x.label}</option>)}</select><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="给申请人的进度说明" className="resize-none rounded-[16px] border border-[color:var(--sauna-line)] bg-[var(--sauna-soft)] p-3 text-sm outline-none"/><button disabled={busy} onClick={()=>onSave(item,status,note)} className="inline-flex h-10 items-center justify-center gap-2 rounded-full bg-[var(--sauna-primary)] text-sm font-semibold text-[var(--sauna-primary-contrast)] disabled:opacity-50"><CheckCircle size={16}/>{busy?"保存中…":"保存状态"}</button></div></div></article>}
