"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, Check, LinkSimple, Plus } from "@phosphor-icons/react";
import { motion } from "motion/react";
import { createSaunaApiClient, humanizeApiError } from "@/lib/sauna-api";
import { useAccessUIStore } from "@/store/access-ui-store";
import { useSaunaStore } from "@/store/sauna-store";
import type { CatalogEntry } from "@/types/sauna";

export function CatalogDetail({ slug }: { slug: string }) {
  const token = useSaunaStore((state) => state.token); const loadWorkspaceAgents = useSaunaStore((state) => state.loadWorkspaceAgents); const openAuth = useAccessUIStore((state) => state.openAuth);
  const [item,setItem]=useState<CatalogEntry>(); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{ void createSaunaApiClient(token).getCatalogEntry(slug).then(setItem).catch((e)=>setError(humanizeApiError(e))); },[slug,token]);
  async function toggle(){ if(!item)return; if(!token){openAuth("protected_action",{kind:"route",returnTo:`/catalog/${slug}`});return;} setBusy(true); try{const api=createSaunaApiClient(token); if(item.installed)await api.removeCatalogAgent(item.agent.id);else await api.installCatalogAgent(item.agent.id);setItem({...item,installed:!item.installed});await loadWorkspaceAgents(token);}catch(e){setError(humanizeApiError(e));}finally{setBusy(false)}}
  if(error&&!item)return <div className="rounded-[30px] bg-[var(--sauna-danger-soft)] p-6 text-[var(--sauna-danger-strong)]">{error}</div>;
  if(!item)return <div className="h-[520px] animate-pulse rounded-[38px] bg-[var(--sauna-soft)]"/>;
  return <section className="pb-10"><Link href="/catalog" className="inline-flex items-center gap-2 text-sm text-[var(--sauna-muted)] hover:text-[var(--sauna-text)]"><ArrowLeft size={16}/> 返回人物大厅</Link><motion.div initial={{opacity:0,y:16}} animate={{opacity:1,y:0}} className="mt-5 overflow-hidden rounded-[38px] border border-[color:var(--sauna-line)] bg-[var(--sauna-panel-strong)] shadow-[var(--sauna-shadow)]"><div className="grid gap-8 p-7 sm:p-10 lg:grid-cols-[.8fr_1.2fr] lg:p-12"><div className="flex min-h-72 flex-col justify-between rounded-[30px] bg-[var(--sauna-soft)] p-8"><span className="text-7xl">{item.agent.avatar_emoji||"🧠"}</span><div><p className="text-sm font-medium text-[var(--sauna-accent-strong)]">{item.categories.join(" / ")||"人物顾问"}</p><h1 className="sauna-display mt-2 text-5xl tracking-[-0.055em]">{item.agent.display_name}</h1><p className="mt-2 text-sm text-[var(--sauna-muted-strong)]">{item.agent.role_summary}</p></div></div><div className="py-2"><p className="text-sm leading-7 text-[var(--sauna-muted-strong)]">{item.summary}</p><div className="mt-7 rounded-[24px] border border-[color:var(--sauna-line)] p-5"><p className="text-sm font-semibold">蒸馏说明</p><p className="mt-2 text-sm leading-7 text-[var(--sauna-muted)]">{item.source_description||"由平台基于公开资料和 nuwa-skill 规范蒸馏，并在上架前完成内容审核。"}</p>{item.source_urls.length?<div className="mt-4 flex flex-wrap gap-2">{item.source_urls.slice(0,4).map((url)=><a key={url} href={url} target="_blank" rel="noreferrer" className="inline-flex items-center gap-1 rounded-full bg-[var(--sauna-soft)] px-3 py-2 text-xs text-[var(--sauna-muted-strong)]"><LinkSimple size={13}/> 资料来源</a>)}</div>:null}</div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><button onClick={()=>void toggle()} disabled={busy} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[var(--sauna-primary)] px-6 text-sm font-semibold text-[var(--sauna-primary-contrast)] disabled:opacity-50">{item.installed?<><Check size={16}/> 已加入智囊团</>:<><Plus size={16}/> 添加到智囊团</>}</button><Link href={`/try/${item.agent.slug}`} className="inline-flex h-12 items-center justify-center gap-2 rounded-full bg-[var(--sauna-soft)] px-6 text-sm font-semibold">先试聊一次 <ArrowRight size={16}/></Link></div>{error?<p className="mt-4 text-sm text-[var(--sauna-danger)]">{error}</p>:null}</div></div></motion.div></section>;
}
