"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { Bell, Check, Megaphone } from "@phosphor-icons/react";
import { AnimatePresence, motion } from "motion/react";
import { createSaunaApiClient } from "@/lib/sauna-api";
import { useSaunaStore } from "@/store/sauna-store";
import type { Inbox } from "@/types/sauna";
export function InboxMenu(){const token=useSaunaStore(s=>s.token);const [open,setOpen]=useState(false);const [inbox,setInbox]=useState<Inbox>();useEffect(()=>{if(token)void createSaunaApiClient(token).getInbox().then(setInbox).catch(()=>undefined)},[token]);if(!token)return null;async function readAll(){await createSaunaApiClient(token).readAllInbox();setInbox(v=>v?{...v,unread_count:0,notifications:v.notifications.map(x=>({...x,read_at:x.read_at||new Date().toISOString()})),announcements:v.announcements.map(x=>({...x,read:true}))}:v)}return <div className="relative"><button onClick={()=>setOpen(v=>!v)} aria-label="通知" className="relative grid size-10 place-items-center rounded-full text-[var(--sauna-muted)] transition hover:bg-[var(--sauna-soft)]"><Bell size={18}/>{inbox?.unread_count?<span className="absolute right-1.5 top-1.5 min-w-4 rounded-full bg-[var(--sauna-danger)] px-1 text-center text-[10px] leading-4 text-white">{Math.min(inbox.unread_count,9)}</span>:null}</button><AnimatePresence>{open?<motion.div initial={{opacity:0,y:8,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:6}} className="absolute right-0 top-12 z-50 w-[min(380px,calc(100vw-2rem))] rounded-[26px] border border-[color:var(--sauna-line)] bg-[var(--sauna-panel-strong)] p-4 shadow-[var(--sauna-shadow)]"><div className="flex items-center justify-between"><strong>消息</strong><button onClick={()=>void readAll()} className="inline-flex items-center gap-1 text-xs text-[var(--sauna-accent-strong)]"><Check size={13}/> 全部已读</button></div><div className="mt-3 max-h-96 overflow-y-auto">{[...(inbox?.notifications??[]).map(x=>({id:x.id,title:x.title,body:x.body,read:Boolean(x.read_at),href:x.linked_request_id?"/catalog":"/catalog"})),...(inbox?.announcements??[]).map(x=>({id:x.id,title:x.title,body:x.summary,read:x.read,href:"/catalog"}))].slice(0,10).map(x=><Link key={x.id} href={x.href} onClick={()=>setOpen(false)} className={`block rounded-[18px] p-3 text-sm transition hover:bg-[var(--sauna-soft)] ${x.read?"opacity-65":""}`}><p className="flex items-center gap-2 font-semibold"><Megaphone size={14}/>{x.title}</p><p className="mt-1 line-clamp-2 text-xs leading-5 text-[var(--sauna-muted)]">{x.body}</p></Link>)}{!inbox?.notifications.length&&!inbox?.announcements.length?<p className="p-5 text-center text-sm text-[var(--sauna-muted)]">还没有新消息。</p>:null}</div></motion.div>:null}</AnimatePresence></div>}
